### ISSUE TITLE
collapsing config into a single .json or .yaml would save some lines (do users really need to set the number of header lines per file?).

### ISSUE THREAD

**Issue by rg727** [IMMM-SFA/statemodify#59]
https://github.com/IMMM-SFA/statemodify/issues/54
https://github.com/openjournals/joss-reviews/issues/6325

**Comment by crvernon** [comment]
These were left as single files with purpose so that users would only have to interact with file types they had specific interests in.  We let the users set details like the number of header lines per file because these actually do change for some StateMod versions / implementations.  We wanted to give users the ability to customize these key things in case they were utilizing custom StateMod versions.  Thanks!
